{"fc0f95d093739f91d182c29aa423c161":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"1ddf522904052035","reportUrl":"https://mahmutovAR.github.io/temp_code/9//#testresult/1ddf522904052035","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f096b6515a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1727433158246,"stop":1727433158248,"duration":2}}]},"db27157d5642a90fdd32c5503255464f":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4118bd1bcbc67826","reportUrl":"https://mahmutovAR.github.io/temp_code/9//#testresult/4118bd1bcbc67826","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f096b52c7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1727433158134,"stop":1727433158136,"duration":2}}]},"05364924c3b260a58f8a062c64b4aa3e":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"242c6fddc0968709","reportUrl":"https://mahmutovAR.github.io/temp_code/9//#testresult/242c6fddc0968709","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f096b4b2470>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1727433158348,"stop":1727433158350,"duration":2}}]},"e3f9b85037ebef9247bcbe1b0024b580":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"cf42bdaebf0d1a3f","reportUrl":"https://mahmutovAR.github.io/temp_code/9//#testresult/cf42bdaebf0d1a3f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f096b462fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1727433158031,"stop":1727433158033,"duration":2}}]},"5ae7b22c107f9d32879d4a3100f4040f":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"3021689abb2df483","reportUrl":"https://mahmutovAR.github.io/temp_code/9//#testresult/3021689abb2df483","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f096b4f6bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1727433157853,"stop":1727433157891,"duration":38}}]}}