{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"UnboundLocalError: local variable 'data_id' referenced before assignment","children":[{"name":"Create a new entity","uid":"884302864fe4f60f","parentUid":"199111ca2db9c44d0d4a5f3792ed2065","status":"broken","time":{"start":1727560454829,"stop":1727560454842,"duration":13},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"Get a single entity","uid":"c4bfe72f49e86eb7","parentUid":"199111ca2db9c44d0d4a5f3792ed2065","status":"broken","time":{"start":1727560455109,"stop":1727560455110,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"Patch an entity","uid":"db389e85d09302a2","parentUid":"199111ca2db9c44d0d4a5f3792ed2065","status":"broken","time":{"start":1727560455331,"stop":1727560455332,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"199111ca2db9c44d0d4a5f3792ed2065"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1163b8b010>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Delete entity","uid":"35c0f55aae1f9152","parentUid":"54692e4c006d61d0113c8ed6b90a9fbd","status":"broken","time":{"start":1727560455002,"stop":1727560455004,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"54692e4c006d61d0113c8ed6b90a9fbd"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1163ac5e40>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Get a list of entities","uid":"d38cb86f7fdf850e","parentUid":"a532065754ff5f5535a88941f961082b","status":"broken","time":{"start":1727560455226,"stop":1727560455228,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"a532065754ff5f5535a88941f961082b"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}